routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if ( Auth::check() ) {
		return view('welcome');	
	} else {
		return redirect('login');
	}
});

Auth::routes();

// admin routes
Route::get('admin/home', 'HomeController@index')->name('home');
Route::get('member/home', 'HomeController@index')->name('member');

// settings
Route::get('settings', 'SettingsController@index')->name('settings');
Route::post('settings/profile', 'SettingsController@profile_update')->name('profile.update');
Route::post('settings/password', 'SettingsController@password_update')->name('password.update');

// Restful Controllers
Route::resources([
	'users' => 'UsersController',
	'roles' => 'RolesController',
]);

resources/views/inc/alert.blade.php
<div class="col-md-12">

    @foreach ( $errors->all() as $message )
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error:</strong> {{ $message }}
        </div>
    @endforeach

    @if ( isset( $success_message ) && $success_message )
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success:</strong> {{ $success_message }}
        </div>
    @endif

    @if ( isset( $error_message ) && $success_message )
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error:</strong> {{ $error_message }}
        </div>
    @endif

    @if ( session('success') )
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success:</strong> {{ session('success') }}
        </div>
    @endif

    @if ( session('error') )
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error:</strong> {{ session('error') }}
        </div>
    @endif

    @if ( session('warning') )
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Warning:</strong> {{ session('warning') }}
        </div>
    @endif

</div>

resources/views/inc/nav.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">

            <li class="nav-header">
                <div class="dropdown profile-element"> 
                    <span>
                        <img alt="image" class="img-circle" src="{{asset('img/profile_small.jpg')}}" />
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> 
                            <span class="block m-t-xs"> 
                                <strong class="font-bold">{{ Auth::user()->name }}</strong>
                            </span> 
                            <span class="text-muted text-xs block">Options <b class="caret"></b></span> 
                        </span> 
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{{ url('settings') }}">Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">JMO</div>
            </li>

            <li>
                <a href="{{ route('home') }}"> 
                    <i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span>
                </a>
            </li>
    
            @if ( Auth::user()->hasRole('admin') )
            <li>
                <a href="{{ route('users.index') }}"> 
                    <i class="fa fa-users"></i> <span class="nav-label">Users</span>
                </a>
            </li>
            <li>
                <a href="{{ route('roles.index') }}"> 
                    <i class="fa fa-lock"></i> <span class="nav-label">User Roles</span>
                </a>
            </li>
            @endif

            <li>
                <a href="{{ route('settings') }}">
                    <i class="fa fa-cogs"></i> <span class="nav-label">Profile Settings</span>
                </a>
            </li>

        </ul>
    </div>
</nav>